name: verify_payment
description: A package for Angolan payment proof validation.
version: 1.0.0

environment:
  sdk: ^3.3.2

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
